### PR TITLE
Revert "Adding OpenCMISS-Osmium to the opencmiss website"

### PR DESCRIPTION
**Pull request by chrispbradley**
Reverts OpenCMISS/website#6

Ummm, I don't think that this pull request conforms to what was agreed. What was agreed was that the collective was emphasised and not the individual. That we are in a state of transition and that whilst new documentation still had projects new documentation was to not have the projects emphasised.

### CODE REVIEW

**Comment by nickerso** [comment]
No, there are many other changes that are required for the website to move to that user-focused view. #6 simply expands the OpenCMISS brand beyond Zinc and Iron and adds in Osmium in the same way that Zinc and Iron are already presented on the website. I'm not proposing to update the entire site at this time just to get Osmium listed.

**Comment by chrispbradley** [comment]
Then just remove the Osmium bit. It is not part of the brand. New docs should not go further down the project path.

Sent from my iPad

On 27/07/2016, at 10:37 AM, David Nickerson <notifications@github.com<mailto:notifications@github.com>> wrote:


No, there are many other changes that are required for the website to move to that user-focused view. #6<https://github.com/OpenCMISS/website/pull/6> simply expands the OpenCMISS brand beyond Zinc and Iron and adds in Osmium in the same way that Zinc and Iron are already presented on the website. I'm not proposing to update the entire site at this time just to get Osmium listed.

**Comment by nickerso** [comment]
Until someone has time to update the website, I don't see anything wrong with adding a description of Osmium to the existing website in the same way that Zinc and Iron are described.

**Comment by chrispbradley** [comment]
Ummm, you changed the definition of OpenCMISS. This was objected to, discussed, resolved and then the request was just pulled in with the objections still in place with no attempt to correct them? How is this even the case??? Yes, the Iron and Zinc parts need to be changed. This was noted to all before they even went in. These have not been corrected despite many comments. Adding more stuff and using past/and present problems as justification is definitely not the way to go. Especially when it would take 5 s to search and replace the (chemical element of choice) with just OpenCMISS in the very small pull request???

Sent from my iPad

On 27/07/2016, at 10:53 AM, David Nickerson <notifications@github.com<mailto:notifications@github.com>> wrote:


Until someone has time to update the website, I don't see anything wrong with adding a description of Osmium to the existing website in the same way that Zinc and Iron are described.

**Pull request merged**
